### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Xiaohantx**
Add name

### CODE REVIEW

**Comment by MSWorkers** [comment]
but why remove someone else's name? 为什么删除别人的名字?

**Comment by waynebaby** [comment]
> but why remove someone else's name? 为什么删除别人的名字?

that is because everyone works concurrently so they get a version is older than yours they may get less names than latest ones, and submit it with less names.

The reviewer need to help with the lost information, correct the conflicts, or no one could submit safely

**Comment by Xiaohantx** [comment]
> 但為什麼要刪除別人的名字？為什麼刪除別人的名字？



> 不要刪除他人的名字



> > 但為什麼要刪除別人的名字？為什麼刪除別人的名字？
> 
> 這是因為每個人都同時工作，所以他們得到的版本比你的版本舊，他們的名字可能比最新版本少，並且用較少的名字提交。
> 
> 審稿人需要幫助處理丟失的信息，糾正衝突，或者沒有人能夠安全地提交

Sorry, I have never deleted the name of someone else, I submitted the request directly after editing on github

The situation is not what I hope, I hope that Reviewers can help correct, thank you

**Comment by Xiaohantx** [comment]
> but why remove someone else's name? 为什么删除别人的名字?



> Do not delete others' names

Sorry, I have never deleted the name of someone else, I submitted the request directly after editing on github

The situation is not what I hope, I hope that Reviewers can help correct, thank you

**Pull request merged**
